all: Makefile.coq
	$(MAKE) -f Makefile.coq all

clean: Makefile.coq
	$(MAKE) -f Makefile.coq cleanall
	rm -f Makefile.coq Makefile.coq.conf

Makefile.coq: _CoqProject
	coq_makefile -f _CoqProject -o Makefile.coq

_CoqProject Makefile: ;

%: Makefile.coq
	$(MAKE) -f Makefile.coq $@

.PHONY: all clean doc doc-clean

# Html documentation ---------------------------------------------------------
# `make doc` renders the sources with rocqnavi
# (https://github.com/affeldt-aist/rocqnavi), which `nix-shell` provides; see
# .nix/rocq-overlays/rocqnavi.  Outside nix, install it with
# `opam pin rocq-navi https://github.com/affeldt-aist/rocqnavi.git`.

DOCDIR = html
GIT_HASH := $(shell git describe --tags --exact-match 2>/dev/null || \
                    git rev-parse --short HEAD)
ROCQ_STDLIB_URL = https://rocq-prover.org/doc/V9.1.0/stdlib/
# NB: mathcomp 2.5 moved eqtype/seq/bigop/... from mathcomp.ssreflect to
# mathcomp.boot; the old namespace 404s, so every reference to those modules
# renders unlinked unless mathcomp.boot is listed below.
MATHCOMP_URL = https://math-comp.github.io/htmldoc_2_5_0/
ANALYSIS_URL = https://math-comp.github.io/analysis/htmldoc/1_16_0/

# File dependency graph, drawn on the index page.  Generated by hand rather
# than through rocqnavi's own -file-graph-from-depend, which mislinks the nodes
# in a flat project; see the script for details.
$(DOCDIR)/dependency_graph.dot: _CoqProject etc/rocqnavi_dependency-graph.sh
	mkdir -p $(DOCDIR)
	etc/rocqnavi_dependency-graph.sh $@ LDL

# Hierarchy-Builder structure graph, likewise.  Needs the .vo files, hence
# the dependency on `all`.
$(DOCDIR)/hierarchy_graph.dot: all etc/rocqnavi_generate-hierarchy-graph.sh
	mkdir -p $(DOCDIR)
	etc/rocqnavi_generate-hierarchy-graph.sh $@

doc: all $(DOCDIR)/dependency_graph.dot $(DOCDIR)/hierarchy_graph.dot
	rocqnavi \
	  -title "LDL $(GIT_HASH)" \
	  -d $(DOCDIR) \
	  -Q . LDL \
	  -coqlib $(ROCQ_STDLIB_URL) \
	  -file-graph $(DOCDIR)/dependency_graph.dot \
	  -structure-graph $(DOCDIR)/hierarchy_graph.dot \
	  -index-blacklist etc/rocqnavi_index-blacklist \
	  -external $(MATHCOMP_URL) mathcomp.boot \
	  -external $(MATHCOMP_URL) mathcomp.algebra \
	  -external $(MATHCOMP_URL) mathcomp.order \
	  -external $(MATHCOMP_URL) mathcomp.fingroup \
	  -external $(MATHCOMP_URL) mathcomp.solvable \
	  -external $(MATHCOMP_URL) mathcomp.field \
	  -external $(ANALYSIS_URL) mathcomp.analysis \
	  -external $(ANALYSIS_URL) mathcomp.classical \
	  -external $(ANALYSIS_URL) mathcomp.reals \
	  ./*.v ./*.glob

doc-clean:
	rm -rf $(DOCDIR)
